on:
  push:
    branches:
      - "main"
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 14 * * *'

jobs:
   run:
    runs-on: ubuntu-latest
    name: Run
    run: |
      docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/leetcode-discord-bot:latest